<!DOCTYPE html>
        <html lang="en">
        <head>
          <title><?=$this->name?></title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
          <script
    			  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
    			  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
    			  crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
          <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        </head>
        <body>
        <div class="container">
        <a href="/file/upload" class="btn btn-primary pull-right" >Go to Upload</a>
        <table id="files-datatable" class="table">
                <thead>
                    <th>#</th>
                    <th>Filename</th>
                    <th>Size</th>
                </thead>
                <tbody>
                    <?php for($i = 0; $i < count($this->files); $i++) { ?>
                        <tr>
                            <td><?=$i + 1?></td>
                            <td><a href="/file/show?file=<?=urlencode($this->files[$i]['file_path'])?>" ><?=$this->files[$i]['filename']?></a></td>
                            <td><?=round($this->files[$i]['size'] / 1024, 2)?> KBs</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery("#files-datatable").DataTable();
            });
        </script>
        </body>
        </html>