 <!DOCTYPE html>
        <html lang="en">
        <head>
          <title><?=$this->name?></title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
          <script
    			  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
    			  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
    			  crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
          <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        </head>
        <body>
        <div class="container">
            <form id="uploader" method="post" action="/file/parse" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="file-input">Upload File: </label>
                    <input id="file-input" name="file" type="file" accept=".txt" class="form-control-file" />
                </div>
                <button type="submit" class="btn btn-primary" title="Submit">Submit</button>
            </form>
        </div>
        <script type="text/javascript">
        </script>
        </body>
        </html>