<!DOCTYPE html>
        <html lang="en">
        <head>
          <title><?=$this->name?></title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
          <link rel="stylesheet" href="https://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
          <script
    			  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
    			  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
    			  crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
          <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        </head>
        <body>
        <div class="container">
            <input type="hidden" name="pass" id="pass" />
            <table id="questions-table">
                <thead>
                    <th>Question</th>
                    <th style="display:none;">Answers</th>
                </thead>
                <tbody>
                    <?php foreach($this->questions as $question) { ?>
                    <tr id="question-id-<?=$question['id']?>">
                        <!--<td><button style="display:none;" class="delete-question" data-question_id="<?php //echo $question['id'];?>" >Delete Question</button></td>-->
                        <td style="display:block;width:60%"><?=$question['question']?></td>
                        <td style="display:block;width:60%"><div class="panel-group">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse-<?=$question['id'];?>">Answers</a>
                      </h4>
                    </div>
                    <div id="collapse-<?=$question['id']?>" class="panel-collapse collapse in">
                      <div class="panel-body">
                          <ul class="list-group">
                              <?php foreach($this->answers[$question['id']] as $answer) { ?>
                              <li class="list-group-item <?=($answer['is_correct'] ? 'list-group-item-success' : '');?>">
                                  <?php if(count($this->answers[$question['id']]) === 1) { ?>
                                        <pre><?=$answer['text']?></pre>
                                  <?php } else { ?>
                                    <?=$answer['text']?>
                                  <?php } ?>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                    </div>
                  </div>
                </div>
                </td>
                </tr>
            <?php } ?>
                </tbody>
            </table>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery("#questions-table").DataTable({"pageLength" : 25, "columnDefs": [
            {
                "targets": [ 1 ],
                "bSortable": false
            }
        ]});
                jQuery("body").on("click", ".delete-question", function(){
                    $button = jQuery(this);
                    var questionId = $button.data("question_id");
                    var password = jQuery("#pass").val();
                        $.ajax({url: "/index/delete", data : {question_id : questionId, pass : password}, type: "POST", success: function(result){
                            if(result == 1) {
                                jQuery("#question-id-" + questionId).remove();
                            } else {
                                alert(result);
                            }
                        }});
                });
            });
        </script>
        </body>
        </html>